export const puzzleList = [
  {puzzle: 'Ache Inks High Sped', answer: 'A King sized bed'},
  {puzzle: 'Abe Odd Hull Luck Oak', answer: 'A bottle of Coke'},
  {puzzle: 'Ace Lip Puff That Hung', answer: 'A slip of the tongue'},
  {puzzle: 'Delete Elmer Made', answer: 'The little mermaid'},
  {puzzle: 'Bat Tree Snot Ink Looted', answer: 'Batteries not included'},
  {puzzle: 'Dew Ache Who Gulls Urge', answer: 'Do a Google search'},
  {puzzle: 'Hide Hen Tickled Wins', answer: 'Identical Twins'},
  {puzzle: 'Hype People Earth Duh Hey', answer: 'Happy Birthday'},
  {puzzle: 'Ice Mail Ask Hunk', answer: 'I smell a skunk'},
  {puzzle: 'Isle Of View', answer: 'I love you'},
  {puzzle: 'It Chief Heat', answer: 'Itchy feet'},
  {puzzle: 'Jog Clay Die Scream', answer: 'Chocolate Ice Cream'},
  {puzzle: 'Kitten Scene Gulf Aisle', answer: 'Get in single file'},
  {puzzle: 'Ladle Rat Rotten Hut', answer: 'little Red Riding Hood'},
  {puzzle: 'Law Duff There Inks', answer: 'Lord of the Rings'},
  {puzzle: 'My Kojak Sun', answer: 'Michael Jackson'},
  {puzzle: 'Pea Sank White', answer: 'Peace and Quiet'},
  {puzzle: 'Space Youl Limp Picks', answer: 'Special Olympics'},
  {puzzle: 'We Shy Worth Hare', answer: 'Wish I was there'},
  {puzzle: 'Wheel Yum Air Ream He', answer: 'Winter Olympic Games'},
  {puzzle: 'Ail Huck Each Arm', answer: 'A lucky charm'},
  {puzzle: 'Honey Duck Hiss', answer: 'I need a kiss'},
  {puzzle: 'Ape Hand Hub Hair', answer: 'A panda bear'},
  {puzzle: 'Abe Who Beat Wrap', answer: 'A Booby Trap'},
  {puzzle: 'These Hound Doff Moo Sick', answer: 'The Sound Of Music'},
  {puzzle: 'Sioux Punk Rack Hearse', answer: 'Soup And Crackers'},
  {puzzle: 'Fur Stand Form Host', answer: 'First And Foremost'},
  {puzzle: 'Mine Ore A Teary Port', answer: 'Minority Report'},
  {puzzle: 'Rot Into Thick Oar', answer: 'Rotten To The Core'},
  {puzzle: 'Thesis Sawn Who Tomb He', answer: 'This Is All New To Me'},
  {puzzle: 'Sea Yule Hater', answer: 'See You Later'},
  {puzzle: 'ake A Suggestion', answer: 'May Cuss Suck Jest Chin'},
  {puzzle: 'Rome He Owe Hand Jewelry Yet', answer: 'Romeo And Juliet'},
  {puzzle: 'Dust Herb Ink Dap Peas', answer: 'Disturbing The Peace'},
  {puzzle: 'Ace Heck Hunch Ants', answer: 'A Second Chance'},
  {puzzle: 'Hype Ledger Legions Tooth Affleck', answer: 'I Pledge Allegiance To The Flag'},
  {puzzle: 'Thief Hearse Late He', answer: 'The First Lady'},
  {puzzle: 'Reese Urchin Deep Element', answer: 'Research And Development'},
  {puzzle: 'Plea Sleeve Amass Itch', answer: 'Please Leave A Message'},
  {puzzle: 'Say Fit Fray Ray Need Hey', answer: 'Save It For A Rainy Day'},
  {puzzle: 'Aim Adder Rough Open Yen', answer: 'A Matter Of Opinion'},
  {puzzle: 'Dust Herb Ink Dap Peas', answer: 'Disturbing The Peace'},
  {puzzle: 'Ace Heck Hunch Ants', answer: 'A Second Chance'},
  {puzzle: 'Plea Center Europe As Ward', answer: 'Please Enter Your Password'},
  {puzzle: 'Fooled Forth Halt', answer: 'Food For Thought'},
  {puzzle: 'Ace Cam Mar Test', answer: 'A Scam Artist'},
  {puzzle: 'Mass Turk Hard', answer: 'MasterCard'},
  {puzzle: 'Tube Row Tacked Ant Surf', answer: 'To Protect And Serve'},
  {puzzle: 'Us It Ease Liquor', answer: 'A City Slicker'},
  {puzzle: 'Sigh Ted Fork Un Tempt', answer: 'Cited For Contempt'},
  {puzzle: 'Peep Elm Hag Oz Scene', answer: 'People Magazine'},
  {puzzle: 'Lay Bird Hey We Kin', answer: 'Labor Day Weekend'},
  {puzzle: 'Deed At Chew Off Lip Buddy', answer: 'The Statue Of Liberty'},
  {puzzle: 'High Weight Who Evan', answer: 'Highway To Heaven'},
  {puzzle: 'Row Linen Thumb Honey', answer: 'Rolling In The Money'},
  {puzzle: 'Nope Odd Den Hose Force Your', answer: 'Nobody Knows For Sure'},
  {puzzle: 'Shack Cough Alt Raids', answer: 'Jack Of All Trades'},
  {puzzle: 'Around Dove Apple Laws', answer: 'A Round Of Applause'},
  {puzzle: 'Neigh Verse Sane Heifer', answer: 'Never Say Never'},
  {puzzle: 'Sit Chores Height Sigh', answer: 'Set Your Sights High'},
  {puzzle: 'Read My Lips', answer: 'Weed Mile Hips'},
  {puzzle: 'Lie Sin Sand Dedges Tray Shun', answer: 'License And Registration'},
  {puzzle: 'Arrow Man Tick Calm Eddy', answer: 'A Romantic Comedy'},
  {puzzle: 'Thin Hey Muff Thick Aim', answer: 'The Name Of The Game'},
  {puzzle: 'Backed Ooze Queer Won', answer: 'Back To Square One'},
  {puzzle: 'Aid Eye Mud Us Sin', answer: 'A Dime A Dozen'},
  {puzzle: 'Tree Chores Hail Fright', answer: 'Treat Yourself Right'},
  {puzzle: 'Nosh Hun Elsie Cure Itty', answer: 'National Security'},
  {puzzle: 'Pea Pill Arf Honey', answer: 'People Are Funny'},
  {puzzle: 'Ewe Hardy Juan Form He', answer: 'You Are The One For Me'},
  {puzzle: 'Weigh Cup Toothy Fax', answer: 'Wake Up To The Facts'},
  {puzzle: 'Eye Screams Hand Witch', answer: 'Ice Cream Sandwich'},
  {puzzle: 'These Oop Ream Kurt', answer: 'The Supreme Court'}
];
